# coding: utf-8

"""
    Find the knowledge in your data

    <h2><img src='/logo.svg' alt='Infactory' height='50'></h2><p><ul><li><a href='/er.svg'>Entity-Relationship Diagram</a></li><li><a href='/er.md'>Documentation</a></li></ul></p>

    The version of the OpenAPI document: 0.5.0
    Contact: support@infactory.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.rbac_api import RBACApi


class TestRBACApi(unittest.TestCase):
    """RBACApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RBACApi()

    def tearDown(self) -> None:
        pass

    def test_create_rbac_endpoint_v1_rbac_post(self) -> None:
        """Test case for create_rbac_endpoint_v1_rbac_post

        Create Rbac Endpoint
        """
        pass

    def test_delete_rbac_endpoint_v1_rbac_rbac_id_delete(self) -> None:
        """Test case for delete_rbac_endpoint_v1_rbac_rbac_id_delete

        Delete Rbac Endpoint
        """
        pass

    def test_get_rbac_by_team_endpoint_v1_rbac_team_team_id_get(self) -> None:
        """Test case for get_rbac_by_team_endpoint_v1_rbac_team_team_id_get

        Get Rbac By Team Endpoint
        """
        pass

    def test_get_rbac_by_user_endpoint_v1_rbac_user_user_id_get(self) -> None:
        """Test case for get_rbac_by_user_endpoint_v1_rbac_user_user_id_get

        Get Rbac By User Endpoint
        """
        pass

    def test_get_rbac_endpoint_v1_rbac_rbac_id_get(self) -> None:
        """Test case for get_rbac_endpoint_v1_rbac_rbac_id_get

        Get Rbac Endpoint
        """
        pass

    def test_update_rbac_endpoint_v1_rbac_rbac_id_patch(self) -> None:
        """Test case for update_rbac_endpoint_v1_rbac_rbac_id_patch

        Update Rbac Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
