# coding: utf-8

"""
    Find the knowledge in your data

    <h2><img src='/logo.svg' alt='Infactory' height='50'></h2><p><ul><li><a href='/er.svg'>Entity-Relationship Diagram</a></li><li><a href='/er.md'>Documentation</a></li></ul></p>

    The version of the OpenAPI document: 0.5.0
    Contact: support@infactory.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infactory_client.api.data_lines_api import DataLinesApi


class TestDataLinesApi(unittest.TestCase):
    """DataLinesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataLinesApi()

    def tearDown(self) -> None:
        pass

    def test_create_dataline_endpoint_v1_datalines_post(self) -> None:
        """Test case for create_dataline_endpoint_v1_datalines_post

        Create Dataline Endpoint
        """
        pass

    def test_create_queryprogram_endpoint_v1_queryprograms_post(self) -> None:
        """Test case for create_queryprogram_endpoint_v1_queryprograms_post

        Create Queryprogram Endpoint
        """
        pass

    def test_create_queryresponse_endpoint_v1_queryresponses_post(self) -> None:
        """Test case for create_queryresponse_endpoint_v1_queryresponses_post

        Create Queryresponse Endpoint
        """
        pass

    def test_delete_dataline_endpoint_v1_datalines_dataline_id_delete(self) -> None:
        """Test case for delete_dataline_endpoint_v1_datalines_dataline_id_delete

        Delete Dataline Endpoint
        """
        pass

    def test_delete_queryprogram_endpoint_v1_queryprograms_queryprogram_id_delete(self) -> None:
        """Test case for delete_queryprogram_endpoint_v1_queryprograms_queryprogram_id_delete

        Delete Queryprogram Endpoint
        """
        pass

    def test_delete_queryresponse_endpoint_v1_queryresponses_queryresponse_id_delete(self) -> None:
        """Test case for delete_queryresponse_endpoint_v1_queryresponses_queryresponse_id_delete

        Delete Queryresponse Endpoint
        """
        pass

    def test_get_dataline_endpoint_v1_datalines_dataline_id_get(self) -> None:
        """Test case for get_dataline_endpoint_v1_datalines_dataline_id_get

        Get Dataline Endpoint
        """
        pass

    def test_get_datalines_endpoint_v1_datalines_project_projects_id_get(self) -> None:
        """Test case for get_datalines_endpoint_v1_datalines_project_projects_id_get

        Get Datalines Endpoint
        """
        pass

    def test_get_queryprogram_endpoint_v1_queryprograms_queryprogram_id_get(self) -> None:
        """Test case for get_queryprogram_endpoint_v1_queryprograms_queryprogram_id_get

        Get Queryprogram Endpoint
        """
        pass

    def test_get_queryprograms_endpoint_v1_queryprograms_dataline_dataline_id_get(self) -> None:
        """Test case for get_queryprograms_endpoint_v1_queryprograms_dataline_dataline_id_get

        Get Queryprograms Endpoint
        """
        pass

    def test_get_queryresponse_endpoint_v1_queryresponses_queryresponse_id_get(self) -> None:
        """Test case for get_queryresponse_endpoint_v1_queryresponses_queryresponse_id_get

        Get Queryresponse Endpoint
        """
        pass

    def test_get_queryresponses_endpoint_v1_queryresponses_get(self) -> None:
        """Test case for get_queryresponses_endpoint_v1_queryresponses_get

        Get Queryresponses Endpoint
        """
        pass

    def test_update_dataline_endpoint_v1_datalines_dataline_id_patch(self) -> None:
        """Test case for update_dataline_endpoint_v1_datalines_dataline_id_patch

        Update Dataline Endpoint
        """
        pass

    def test_update_queryprogram_endpoint_v1_queryprograms_queryprogram_id_patch(self) -> None:
        """Test case for update_queryprogram_endpoint_v1_queryprograms_queryprogram_id_patch

        Update Queryprogram Endpoint
        """
        pass

    def test_update_queryresponse_endpoint_v1_queryresponses_queryresponse_id_patch(self) -> None:
        """Test case for update_queryresponse_endpoint_v1_queryresponses_queryresponse_id_patch

        Update Queryresponse Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
