# coding: utf-8

"""
    Find the knowledge in your data

    <h2><img src='/logo.svg' alt='Infactory' height='50'></h2><p><ul><li><a href='/er.svg'>Entity-Relationship Diagram</a></li><li><a href='/er.md'>Documentation</a></li></ul></p>

    The version of the OpenAPI document: 0.5.0
    Contact: support@infactory.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infactory_client.api.actions_api import ActionsApi


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActionsApi()

    def tearDown(self) -> None:
        pass

    def test_analyze_data_endpoint_v1_actions_load_analyze_project_id_dataobject_id_post(self) -> None:
        """Test case for analyze_data_endpoint_v1_actions_load_analyze_project_id_dataobject_id_post

        Analyze Data Endpoint
        """
        pass

    def test_ask_endpoint_v1_actions_ask_transform_file_id_dataline_id_post(self) -> None:
        """Test case for ask_endpoint_v1_actions_ask_transform_file_id_dataline_id_post

        Ask Endpoint
        """
        pass

    def test_compile_query_endpoint_v1_actions_ask_compile_transform_file_id_dataline_id_post(self) -> None:
        """Test case for compile_query_endpoint_v1_actions_ask_compile_transform_file_id_dataline_id_post

        Compile Query Endpoint
        """
        pass

    def test_convert_data_endpoint_v1_actions_load_convert_project_id_dataobject_id_post(self) -> None:
        """Test case for convert_data_endpoint_v1_actions_load_convert_project_id_dataobject_id_post

        Convert Data Endpoint
        """
        pass

    def test_evaluate_query_endpoint_v1_actions_ask_evaluate_query_program_id_transform_file_id_dataline_id_post(self) -> None:
        """Test case for evaluate_query_endpoint_v1_actions_ask_evaluate_query_program_id_transform_file_id_dataline_id_post

        Evaluate Query Endpoint
        """
        pass

    def test_format_response_endpoint_v1_actions_ask_format_query_program_id_query_response_id_dataline_id_post(self) -> None:
        """Test case for format_response_endpoint_v1_actions_ask_format_query_program_id_query_response_id_dataline_id_post

        Format Response Endpoint
        """
        pass

    def test_generate_queries_endpoint_v1_actions_generate_queries_transform_file_id_dataline_id_post(self) -> None:
        """Test case for generate_queries_endpoint_v1_actions_generate_queries_transform_file_id_dataline_id_post

        Generate Queries Endpoint
        """
        pass

    def test_load_data_endpoint_v1_actions_load_project_id_post(self) -> None:
        """Test case for load_data_endpoint_v1_actions_load_project_id_post

        Load Data Endpoint
        """
        pass

    def test_prepare_data_endpoint_v1_actions_load_prepare_project_id_parquet_file_id_dataline_file_id_post(self) -> None:
        """Test case for prepare_data_endpoint_v1_actions_load_prepare_project_id_parquet_file_id_dataline_file_id_post

        Prepare Data Endpoint
        """
        pass

    def test_update_compile_query_endpoint_v1_actions_ask_compile_update_query_program_id_transform_file_id_dataline_id_post(self) -> None:
        """Test case for update_compile_query_endpoint_v1_actions_ask_compile_update_query_program_id_transform_file_id_dataline_id_post

        Update Compile Query Endpoint
        """
        pass

    def test_upload_data_endpoint_v1_actions_load_upload_project_id_datasource_id_post(self) -> None:
        """Test case for upload_data_endpoint_v1_actions_load_upload_project_id_datasource_id_post

        Upload Data Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
