# coding: utf-8

"""
    Find the knowledge in your data

    <h2><img src='/logo.svg' alt='Infactory' height='50'></h2><p><ul><li><a href='/er.svg'>Entity-Relationship Diagram</a></li><li><a href='/er.md'>Documentation</a></li></ul></p>

    The version of the OpenAPI document: 0.5.0
    Contact: support@infactory.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infactory_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_login_v1_authentication_token_post(self) -> None:
        """Test case for login_v1_authentication_token_post

        Login
        """
        pass

    def test_read_users_me_v1_authentication_me_get(self) -> None:
        """Test case for read_users_me_v1_authentication_me_get

        Read Users Me
        """
        pass

    def test_signup_v1_authentication_signup_post(self) -> None:
        """Test case for signup_v1_authentication_signup_post

        Signup
        """
        pass


if __name__ == '__main__':
    unittest.main()
