# coding: utf-8

"""
    Find the knowledge in your data

    <h2><img src='/logo.svg' alt='Infactory' height='50'></h2><p><ul><li><a href='/er.svg'>Entity-Relationship Diagram</a></li><li><a href='/er.md'>Documentation</a></li></ul></p>

    The version of the OpenAPI document: 0.5.0
    Contact: support@infactory.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization_endpoint_v1_orgs_post(self) -> None:
        """Test case for create_organization_endpoint_v1_orgs_post

        Create Organization Endpoint
        """
        pass

    def test_delete_organization_endpoint_v1_orgs_organization_id_delete(self) -> None:
        """Test case for delete_organization_endpoint_v1_orgs_organization_id_delete

        Delete Organization Endpoint
        """
        pass

    def test_get_organization_by_clerk_id_endpoint_v1_orgs_clerk_clerk_org_id_get(self) -> None:
        """Test case for get_organization_by_clerk_id_endpoint_v1_orgs_clerk_clerk_org_id_get

        Get Organization By Clerk Id Endpoint
        """
        pass

    def test_get_organization_endpoint_v1_orgs_organization_id_get(self) -> None:
        """Test case for get_organization_endpoint_v1_orgs_organization_id_get

        Get Organization Endpoint
        """
        pass

    def test_get_organizations_endpoint_v1_orgs_get(self) -> None:
        """Test case for get_organizations_endpoint_v1_orgs_get

        Get Organizations Endpoint
        """
        pass

    def test_move_organization_endpoint_v1_orgs_organization_id_move_post(self) -> None:
        """Test case for move_organization_endpoint_v1_orgs_organization_id_move_post

        Move Organization Endpoint
        """
        pass

    def test_update_organization_endpoint_v1_orgs_organization_id_patch(self) -> None:
        """Test case for update_organization_endpoint_v1_orgs_organization_id_patch

        Update Organization Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
