# coding: utf-8

"""
    Find the knowledge in your data

    <h2><img src='/logo.svg' alt='Infactory' height='50'></h2><p><ul><li><a href='/er.svg'>Entity-Relationship Diagram</a></li><li><a href='/er.md'>Documentation</a></li></ul></p>

    The version of the OpenAPI document: 0.5.0
    Contact: support@infactory.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Credentials(BaseModel):
    """
    Represents a credentials record
    """ # noqa: E501
    id: StrictStr
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    metadata: Optional[Any] = None
    datasource_id: Optional[StrictStr] = None
    team_id: Optional[StrictStr] = None
    organization_id: Optional[StrictStr] = None
    infrastructure_id: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    datasources: Optional[Datasources] = None
    infrastructure: Optional[Infrastructure] = None
    organizations: Optional[Organizations] = None
    teams: Optional[Teams] = None
    secrets: Optional[List[Secrets]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "metadata", "datasource_id", "team_id", "organization_id", "infrastructure_id", "created_at", "updated_at", "datasources", "infrastructure", "organizations", "teams", "secrets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Credentials from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of datasources
        if self.datasources:
            _dict['datasources'] = self.datasources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of infrastructure
        if self.infrastructure:
            _dict['infrastructure'] = self.infrastructure.to_dict()
        # override the default output from pydantic by calling `to_dict()` of organizations
        if self.organizations:
            _dict['organizations'] = self.organizations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of teams
        if self.teams:
            _dict['teams'] = self.teams.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in secrets (list)
        _items = []
        if self.secrets:
            for _item_secrets in self.secrets:
                if _item_secrets:
                    _items.append(_item_secrets.to_dict())
            _dict['secrets'] = _items
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if datasource_id (nullable) is None
        # and model_fields_set contains the field
        if self.datasource_id is None and "datasource_id" in self.model_fields_set:
            _dict['datasource_id'] = None

        # set to None if team_id (nullable) is None
        # and model_fields_set contains the field
        if self.team_id is None and "team_id" in self.model_fields_set:
            _dict['team_id'] = None

        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organization_id'] = None

        # set to None if infrastructure_id (nullable) is None
        # and model_fields_set contains the field
        if self.infrastructure_id is None and "infrastructure_id" in self.model_fields_set:
            _dict['infrastructure_id'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if datasources (nullable) is None
        # and model_fields_set contains the field
        if self.datasources is None and "datasources" in self.model_fields_set:
            _dict['datasources'] = None

        # set to None if infrastructure (nullable) is None
        # and model_fields_set contains the field
        if self.infrastructure is None and "infrastructure" in self.model_fields_set:
            _dict['infrastructure'] = None

        # set to None if organizations (nullable) is None
        # and model_fields_set contains the field
        if self.organizations is None and "organizations" in self.model_fields_set:
            _dict['organizations'] = None

        # set to None if teams (nullable) is None
        # and model_fields_set contains the field
        if self.teams is None and "teams" in self.model_fields_set:
            _dict['teams'] = None

        # set to None if secrets (nullable) is None
        # and model_fields_set contains the field
        if self.secrets is None and "secrets" in self.model_fields_set:
            _dict['secrets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Credentials from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "metadata": AnyOf.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "datasource_id": obj.get("datasource_id"),
            "team_id": obj.get("team_id"),
            "organization_id": obj.get("organization_id"),
            "infrastructure_id": obj.get("infrastructure_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "datasources": Datasources.from_dict(obj["datasources"]) if obj.get("datasources") is not None else None,
            "infrastructure": Infrastructure.from_dict(obj["infrastructure"]) if obj.get("infrastructure") is not None else None,
            "organizations": Organizations.from_dict(obj["organizations"]) if obj.get("organizations") is not None else None,
            "teams": Teams.from_dict(obj["teams"]) if obj.get("teams") is not None else None,
            "secrets": [Secrets.from_dict(_item) for _item in obj["secrets"]] if obj.get("secrets") is not None else None
        })
        return _obj

from openapi_client.models.datasources import Datasources
from openapi_client.models.infrastructure import Infrastructure
from openapi_client.models.organizations import Organizations
from openapi_client.models.secrets import Secrets
from openapi_client.models.teams import Teams
# TODO: Rewrite to not use raise_errors
Credentials.model_rebuild(raise_errors=False)

