# coding: utf-8

"""
    Find the knowledge in your data

    <h2><img src='/logo.svg' alt='Infactory' height='50'></h2><p><ul><li><a href='/er.svg'>Entity-Relationship Diagram</a></li><li><a href='/er.md'>Documentation</a></li></ul></p>

    The version of the OpenAPI document: 0.5.0
    Contact: support@infactory.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Datalines(BaseModel):
    """
    This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.     
    """ # noqa: E501
    id: StrictStr
    name: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    deleted_at: Optional[datetime] = None
    dataobject_id: Optional[StrictStr] = None
    schema_code: Optional[StrictStr] = None
    project_id: Optional[StrictStr] = None
    dataobjects: Optional[Dataobjects] = None
    projects: Optional[Projects] = None
    queryprograms: Optional[List[Queryprograms]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "created_at", "updated_at", "deleted_at", "dataobject_id", "schema_code", "project_id", "dataobjects", "projects", "queryprograms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Datalines from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dataobjects
        if self.dataobjects:
            _dict['dataobjects'] = self.dataobjects.to_dict()
        # override the default output from pydantic by calling `to_dict()` of projects
        if self.projects:
            _dict['projects'] = self.projects.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in queryprograms (list)
        _items = []
        if self.queryprograms:
            for _item_queryprograms in self.queryprograms:
                if _item_queryprograms:
                    _items.append(_item_queryprograms.to_dict())
            _dict['queryprograms'] = _items
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        # set to None if dataobject_id (nullable) is None
        # and model_fields_set contains the field
        if self.dataobject_id is None and "dataobject_id" in self.model_fields_set:
            _dict['dataobject_id'] = None

        # set to None if schema_code (nullable) is None
        # and model_fields_set contains the field
        if self.schema_code is None and "schema_code" in self.model_fields_set:
            _dict['schema_code'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if dataobjects (nullable) is None
        # and model_fields_set contains the field
        if self.dataobjects is None and "dataobjects" in self.model_fields_set:
            _dict['dataobjects'] = None

        # set to None if projects (nullable) is None
        # and model_fields_set contains the field
        if self.projects is None and "projects" in self.model_fields_set:
            _dict['projects'] = None

        # set to None if queryprograms (nullable) is None
        # and model_fields_set contains the field
        if self.queryprograms is None and "queryprograms" in self.model_fields_set:
            _dict['queryprograms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Datalines from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "deleted_at": obj.get("deleted_at"),
            "dataobject_id": obj.get("dataobject_id"),
            "schema_code": obj.get("schema_code"),
            "project_id": obj.get("project_id"),
            "dataobjects": Dataobjects.from_dict(obj["dataobjects"]) if obj.get("dataobjects") is not None else None,
            "projects": Projects.from_dict(obj["projects"]) if obj.get("projects") is not None else None,
            "queryprograms": [Queryprograms.from_dict(_item) for _item in obj["queryprograms"]] if obj.get("queryprograms") is not None else None
        })
        return _obj

from openapi_client.models.dataobjects import Dataobjects
from openapi_client.models.projects import Projects
from openapi_client.models.queryprograms import Queryprograms
# TODO: Rewrite to not use raise_errors
Datalines.model_rebuild(raise_errors=False)

